version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=kendamais-server
    ports:
      - "5432:5432"
    networks:
      - kendamaisnetwork
    restart: unless-stopped

networks:
  kendamaisnetwork: